# Generated by Django 5.0.2 on 2024-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='media\\events-images'),
        ),
    ]
