"""
Django settings for FYP project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r(0x67=%4ckz82x8u)&0gfwcqp+0h+z3k!1i1om8n16k3hw*+i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTHENTICATION_BACKENDS = [
    'Authentication.authentication_backends.CustomBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Application definition

INSTALLED_APPS = [
    'Authentication', 
    'Events',
    'Project',
    'Problem',
    'UserProfiles',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'FYP.session_monitoring_middleware.SessionMonitoringMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
   
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#SESSION ENGINE 
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Session settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = False 
SESSION_COOKIE_SECURE = False  # Only send cookies over HTTPS
SESSION_COOKIE_HTTPONLY = False # Prevent client-side access to cookies



ROOT_URLCONF = 'FYP.urls'
LOGIN_URL = '/Authentication/login/'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FYP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fypdatabase',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'asma658@21#i',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    os.path.join(BASE_DIR,'Authentication','static'),
]

MEDIA_ROOT = BASE_DIR /"media"

MEDIA_URL = "/media/"


 # Configure email backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  #appropriate port for your SMTP server 
EMAIL_HOST_USER = 'asmaimran658@gmail.com'
EMAIL_HOST_PASSWORD = 'rdcg vjpn lvvo vewd'
EMAIL_USE_TLS = True

#Loggings
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'email': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'C:\\Users\\dell\\Documents\\Django\\Logs\\email.log',  # Specify the path to your log file
        },
    },
    'loggers': {
        'django.core.mail': {
            'handlers': ['email'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# AUTH_USER_MODEL = 'Authentication.SignupPmo'

#Iframes
X_FRAME_OPTIONS = 'SAMEORIGIN'

