# Generated by Django 5.0.2 on 2024-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_signuppmo_signupstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuppmo',
           name='cnic',
           field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='signupstudent',
           name='cnic',
           field=models.CharField(max_length=13),
        ),
    ]
