# Generated by Django 5.0.2 on 2024-02-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_signuppmo_cnic_alter_signupstudent_cnic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuppmo',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='signupstudent',
            name='cnic',
        ),
    ]
