# Generated by Django 5.0.2 on 2024-02-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_remove_signuppmo_cnic_remove_signupstudent_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuppmo',
            name='cnic',
            field=models.CharField(default=1234567890123, max_length=13),
        ),
        migrations.AddField(
            model_name='signuppmo',
            name='country',
            field=models.CharField(default='Pakistan', max_length=30),
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default='3.55', max_digits=4),
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='cnic',
            field=models.CharField(default='1234567890123', max_length=13),
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='country',
            field=models.CharField(default='Pakistan', max_length=30),
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='result_card',
            field=models.FileField(default=None, max_length=250, upload_to='result-card/'),
        ),
        migrations.AlterField(
            model_name='signupstudent',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
    ]
