# Generated by Django 5.0.2 on 2024-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_signuppmo_cnic_signuppmo_country_signupstudent_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupstudent',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default='3.55', max_digits=4),
        ),
    ]
