# Generated by Django 5.0.2 on 2024-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_signupstudent_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupstudent',
            name='qualification',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
