# Generated by Django 5.0.2 on 2024-02-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_alter_signupstudent_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupstudent',
            name='cnic',
        ),
    ]
