# Generated by Django 5.0.2 on 2024-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_remove_signupstudent_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuppmo',
            name='cnic',
            field=models.CharField(default=3719862345281, max_length=13),
        ),
    ]
