# Generated by Django 5.0.2 on 2024-02-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_alter_signuppmo_cnic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuppmo',
            name='cnic',
        ),
    ]
