# Generated by Django 5.0.2 on 2024-02-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_remove_signuppmo_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuppmo',
            name='cnic',
            field=models.CharField(default=3719862345281, max_length=13),
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='cnic',
            field=models.CharField(default='1234567890123', max_length=13),
        ),
    ]
