# Generated by Django 5.0.2 on 2024-02-29 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_alter_signuppmo_cnic_alter_signuppmo_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuppmo',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='signupstudent',
            name='cnic',
        ),
    ]
