# Generated by Django 5.0.2 on 2024-02-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_remove_signuppmo_cnic_remove_signupstudent_cnic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupPmo',
        ),
        migrations.DeleteModel(
            name='SignupStudent',
        ),
    ]
