# Generated by Django 5.0.2 on 2024-02-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_delete_signuppmo_delete_signupstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('confirm_password', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SignupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=50)),
                ('cgpa', models.DecimalField(decimal_places=2, default='3.55', max_digits=4)),
                ('password', models.CharField(max_length=8)),
                ('confirm_password', models.CharField(max_length=8)),
                ('result_card', models.FileField(default=None, max_length=250, upload_to='result-card/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
            ],
        ),
    ]
