# Generated by Django 5.0.2 on 2024-02-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_signuppmo_signupstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='SignupPmo',
        ),
        migrations.DeleteModel(
            name='SignupStudent',
        ),
    ]
