# Generated by Django 5.0.2 on 2024-03-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0019_alter_signuppmo_cnic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupStudent',
        ),
    ]
