# Generated by Django 5.0.2 on 2024-03-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0021_signupstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupstudent',
            old_name='institute_name',
            new_name='institutename',
        ),
    ]
