# Generated by Django 5.0.2 on 2024-03-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0027_alter_signupstudent_result_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupStudent',
        ),
    ]
