# Generated by Django 5.0.2 on 2024-03-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0029_signupstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupstudent',
            name='resultcard',
            field=models.FileField(upload_to='result-card/'),
        ),
    ]
