# Generated by Django 5.0.2 on 2024-03-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0030_alter_signupstudent_resultcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
