# Generated by Django 5.0.2 on 2024-03-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0031_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupStudent',
        ),
    ]
