# Generated by Django 5.0.2 on 2024-03-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0033_signupstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupStudent',
        ),
    ]
