# Generated by Django 5.0.2 on 2024-03-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0038_alter_signupstudent_resultcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupPmo',
        ),
        migrations.DeleteModel(
            name='SignupStudent',
        ),
    ]
