# Generated by Django 5.0.2 on 2024-03-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0042_signupstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupPmo',
        ),
        migrations.DeleteModel(
            name='SignupStudent',
        ),
    ]
