# Generated by Django 5.0.2 on 2024-03-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0048_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupPmo',
        ),
        migrations.DeleteModel(
            name='SignupStudent',
        ),
    ]
