# Generated by Django 5.0.2 on 2024-03-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0050_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='project',
            new_name='student',
        ),
    ]
