# Generated by Django 5.0.2 on 2024-03-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0051_rename_project_skill_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuppmo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
