# Generated by Django 5.0.2 on 2024-04-01 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0053_customuser_delete_signuppmo_remove_skill_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.FileField(upload_to='profile-pic-pmo/')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('qualification', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('country', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('contactnumber', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.FileField(upload_to='profile-pic-student/')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('institutename', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('country', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=50)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contactnumber', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Authentication.signupstudent')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
