# Generated by Django 5.0.2 on 2024-04-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0054_signuppmo_signupstudent_skill_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuppmo',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signupstudent',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
