# Generated by Django 5.0.2 on 2024-03-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_language_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
