# Generated by Django 5.0.2 on 2024-03-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleimage', models.FileField(upload_to='project-title-image/')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('web', 'Web Development'), ('app', 'App Development'), ('hardware', 'Hardware Development'), ('rnd', 'Research and Development')], max_length=20)),
                ('team_members', models.TextField()),
                ('resultcard', models.FileField(upload_to='resultcard/')),
                ('booklet', models.FileField(upload_to='booklet/')),
                ('githuburl', models.URLField()),
                ('video', models.FileField(upload_to='videos/')),
                ('multimedia', models.FileField(upload_to='multimedia/')),
                ('languages', models.ManyToManyField(to='Project.language')),
                ('skills', models.ManyToManyField(to='Project.skill')),
                ('technologies', models.ManyToManyField(to='Project.technology')),
            ],
        ),
    ]
