# Generated by Django 5.0.2 on 2024-03-25 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
