# Generated by Django 5.0.2 on 2024-03-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='percentage',
            new_name='proficiency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='titleimage',
        ),
    ]
