# Generated by Django 5.0.2 on 2024-03-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_rename_percentage_skill_proficiency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='proficiency',
        ),
    ]
