# Generated by Django 5.0.2 on 2024-04-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='project',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='project',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='project',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Multimedia',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
