# Generated by Django 5.0.2 on 2024-04-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_remove_project_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
