# Generated by Django 5.0.2 on 2024-04-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0017_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
