# Generated by Django 5.0.2 on 2024-04-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0018_notificationtable_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notificationtable',
        ),
    ]
