# Generated by Django 5.0.2 on 2024-04-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0022_project_multimedia_language_skill_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='project',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='project',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='project',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Multimedia',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
