# Generated by Django 5.0.2 on 2024-04-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0024_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
