# Generated by Django 5.0.2 on 2024-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('c1', 'Performance Problem'), ('c2', 'Navigation Issues'), ('c3', 'Form and Input Issues'), ('c4', 'Security Concerns'), ('c5', 'Content-related Issues'), ('c6', 'Functionality Issues'), ('c7', 'Login and Authentication Issues')], max_length=2)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('description', models.TextField()),
            ],
        ),
    ]
